name: Build

on:
  push:
    branches:
      - cicd

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '[16.4,16.5)'
        msbuild-architecture: x64
        
    - name: Build x64 with MSBuild
      run: |
        msbuild VX-AP.sln /p:Configuration=Release

    - name: Build x86 with MSBuild
      run: |
        msbuild VX-AP.sln /p:Configuration=Release /p:Platform=Win32
