name: Build

on:
  push:
    branches:
      - cicd

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build with MSBuild (Release x64)
      run: |
        msbuild VX-API.sln /p:Configuration=Release

    - name: Build with MSBuild (Release x86)
      run: |
        msbuild VX-API.sln /p:Configuration=Release /p:Platform=Win32

